#!/bin/bash

###############  Install and config datatorrent  ###########################
#install datatorrent
sh /tmp/datatorrent.bin -s /tmp/dt-site.xml

#create hdfs root directory
hadoop fs -mkdir -p /user/dtadmin/datatorrent
hadoop fs -chown -R dtadmin /user/dtadmin


#Add datatorrent to welcome.py script
#sed -i '/status_win.addstr(2,2/a \
#    status_win.addstr(3,2,"Please go to http://%s:9090/static/#/docs/welcome.md to begin with your datatorrent experience!(user/pass:dtadmin/dtamin)" % ip)' /opt/startup/welcome.py


curl -c /tmp/cookie-jar -XPOST -H "Content-Type: application/json" \
-d '{"userName":"dtadmin","password":"dtadmin"}' \
http://localhost:9090/ws/v2/login

#config datatorrent
curl -b /tmp/cookie-jar -H "Content-Type: application/json" \
-X PuT -d '{name:"dt.dfsRootDirectory", value:"/user/dtadmin/datatorrent"}' \
http://localhost:9090/ws/v2/config/properties/dt.dfsRootDirectory

#config license
mv /tmp/sandbox_license /opt/datatorrent/current/sandbox_license
curl -b /tmp/cookie-jar -H "Content-Type: application/json" \
-X PuT -d '{name:"dt.license.file", value:"/opt/datatorrent/current/sandbox_license"}' \
http://localhost:9090/ws/v2/config/properties/dt.license.file

#finish configuration
curl -b /tmp/cookie-jar -H "Content-Type: application/json" \
-X PuT -d '{name:"dt.configStatus", value:"complete"}' \
http://localhost:9090/ws/v2/config/properties/dt.configStatus

sleep 10s

#import demos for sandbox
curl -b /tmp/cookie-jar -H "Content-Type: application/json" \
-XPOST -d '{files: ["pi-demo-3.0.0.apa", "twitter-demo-3.0.0.apa", "mobile-demo-3.0.0.apa"]}' \
http://localhost:9090/ws/v2/appPackages/import

mv /tmp/ui /opt/datatorrent/current/demos/ui

cd /opt/datatorrent/current/demos/ui
sh install.sh

# remove the ^M generated by copy from windows host machine
dos2unix /etc/init.d/dtdemos
chmod a+x /etc/init.d/dtdemos
chkconfig --add dtdemos
chkconfig --level 234 dtdemos on


#TODO clean up the files
